# Site settings
title: Fotonic
email:
description:
footer_text: 'Made with <span class="icon-favorite pulse"></span> by people.'
baseurl:

# Social usernames
twitter_username:
github_username:  fotonic
dribbble_username:
instagram_username:
email:

# data
authors:
  andrea:
    display_name: Andrea Baker
    avatar: https://avatars2.githubusercontent.com/u/9620147?v=3&s=400
    bio: Front-end designer, artist, cat lover & wine enthusiast
    about_text: When Andrea isn't watching cat videos shes at a Cincinnati meet up.
    email:
    web:
    twitter: Andreambaker8
    twitter_url: http://twitter.com/Andreambaker8
    github: ambaker888
  chip:
    display_name: Chip Eyler
    avatar: https://avatars2.githubusercontent.com/u/3611075?v=3&s=460
    bio: Ruby on Rails developer, maker, musician & bearded
    about_text: Chip is a full-stack Ruby developer, musician & maker with a passion for building things. He's also never done Karaoke.
    email:
    web:
    twitter: freqn
    twitter_url: http://twitter.com/freqn
    github: freqn
  anthony:
    display_name: Anthony Isaacs
    avatar: https://avatars2.githubusercontent.com/u/10109984
    bio: Angular/Rails developer with interests in data vis, functional programming, & escapist fiction
    email:
    web:
    twitter: nthony_i
    github: AnthonyIsaacs

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true

gems:
  - jekyll-gist
