# Site settings
title: Fotonic
email: example@example.com
description:
footer_text: 'Made with <span class="icon-favorite pulse"></span> by people.'
baseurl:

# Social usernames
twitter_username:
github_username:  fotonic
dribbble_username:
instagram_username:
email: example@example.com

# data
authors:
  andrea:
    display_name: Andrea Baker
    avatar: https://avatars2.githubusercontent.com/u/9620147?v=3&s=400
    email:
    web:
    twitter: Andreambaker8
    github: ambaker888
  chip:
    display_name: Chip Eyler
    avatar: https://avatars2.githubusercontent.com/u/9620147?v=3&s=400
    email:
    web:
    twitter: freqn
    github: freqn

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true

gems:
  - jekyll-gist
